name: Lint Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Versão atualizada

      - name: Set up Python
        uses: actions/setup-python@v5  # Versão atualizada
        with:
          python-version: '3.12'      # Versão estável em 2026

      - name: Install Linting Tools
        run: pip install flake8

      - name: Run Flake8
        # O ponto '.' garante que ele procure em todas as subpastas (knowledge-run, experimenting, etc.)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics